const asyncHandler = require("express-async-handler")
const axios = require("axios")

const aiController = asyncHandler(async(req, res)=>{
    const { prompt } = req.body //question from the user
    try{
        const response = await axios.post("https://api.openai.com/v1/completions",{
            model: "gpt-3.5-turbo-instruct",
            prompt,  //put the question in
            max_tokens: 10 //length of the output generated by the AI model
        },
        {
            headers: {
                Authorization: `Bearer ${process.env.OPENAI_KEY}`,
                "Content-Type": "application/json" //return type
            }
        })
        console.log(response)
        return res.json({
            success: true,
            response: response.data // Assuming you want to send back the data received from OpenAI
        });
    }
    
    catch(error){
        console.error(error);
        // Send an error response back to the client
        res.status(500).json({
            success: false,
            message: error.message
        });
    }
})

module.exports = aiController